spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/metms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowPublicKeyRetrieval=true
        username: root
        password: 123456

mybatis-plus:
    mapper-locations: classpath:com/meinil/metms/server/mapper/*.xml # sql映射文件位置
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token-secret: hahahah
token-time: 100